runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /ajax/.*
  script: main.app
  secure: always

- url: /(.+)
  static_files: static/\1
  upload: static/.*
  secure: always
  expiration: 30d
  http_headers:
    Cache-Control: 'public, max-age=2592000'

- url: /.*
  static_files: static/index.html
  upload: static/index.html
  secure: always
  expiration: 30d
  http_headers:
    Cache-Control: 'public, max-age=2592000'
