runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /ajax/.*
  script: main.app
  secure: always

- url: /assets
  static_dir: static/assets
  secure: always
  expiration: 10m
  http_headers:
    Cache-Control: 'public, max-age=600'

- url: /robots.txt
  static_files: static/assets/robots.txt
  upload: static/assets/robots.txt
  secure: always

- url: /sitemap.xml
  static_files: static/assets/sitemap.xml
  upload: static/assets/sitemap.xml
  secure: always

- url: /pages
  static_dir: static/pages
  secure: always
  expiration: 10m
  http_headers:
    Cache-Control: 'public, max-age=600'

- url: /.*
  script: main.app
