runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /ajax/.*
  script: main.app
  secure: always

- url: /assets
  static_dir: static/assets
  secure: always
  expiration: 10m
  http_headers:
    Cache-Control: 'public, max-age=600'

- url: /pages
  static_dir: static/pages
  secure: always
  expiration: 10m
  http_headers:
    Cache-Control: 'public, max-age=600'

- url: /.*
  static_files: static/pages/index.html
  upload: static/pages/index.html
  secure: always
  expiration: 10m
  http_headers:
    Cache-Control: 'public, max-age=600'
    Vary: Accept-Encoding

- url: /.*
  script: main.app
